// ── 反激变压器设计 · 公式推导（单一来源）──
// 商用版：修正 Lcrit 精确式、补次级 RMS，新增窗口填充/ΔB饱和/损耗温升/漏感应力/磁芯迭代。
export const flybackDerivation = [
  {
    title: '① 能量守恒：输入功率',
    lines: [
      `反激变换器本质是一个隔离型 BUCK-BOOST，`,
      `开关管 ON 时储能于变压器漏感+原边电感，OFF 时释放到副边。`,
      ``,
      `根据能量守恒：`,
      `  Ppri = Pout / η`,
      `其中 η 包含开关损耗、铜损、铁损、二极管压降损耗等。`,
      `最低输入电压时最恶劣——此时 D 最大、电流峰值最高。`,
    ],
  },
  {
    title: '② 匝比 n = VOR / Vsec —— 为什么这么定？',
    lines: [
      `反射电压 VOR 是开关管 OFF 时折算到原边的副边电压。`,
      `由变压器同名端关系：`,
      `  VOR / Vo' = Np / Ns = n   （Vo' = Vo + Vf，含二极管压降）`,
      `所以 n = VOR / (Vo + Vf)。`,
      ``,
      `VOR 的选择权衡：`,
      `  • 太高 → D 越大 → 占空比更接近上限，MOSFET 与输出二极管耐压更高`,
      `  • 太低 → D 越小 → 低压输入时原边峰值电流升高 → 铜损/MOSFET Rds(on) 损耗↑`,
      `  • 同时 VOR 也决定 MOSFET 耐压：Vsw = Vin(max)√2 + VOR + 漏感尖峰`,
      `    例：265VAC → 375V + 120V + 尖峰 ≈ 515V → 选 650V MOSFET`,
    ],
  },
  {
    title: '③ 最大占空比 Dmax —— 从伏秒平衡推导',
    lines: [
      `稳态时变压器原边在一个周期内的净伏秒积为零（否则磁芯饱和）。`,
      `ON 期间：V_Lp = Vdc，持续时间为 DTs`,
      `OFF 期间：V_Lp = -VOR，持续时间为 (1-D)Ts`,
      ``,
      `伏秒平衡：Vdc·D = VOR·(1-D)  →  Dmax = VOR/(Vdc+VOR)`,
      `最低 Vin 时 D 最大——这是最恶劣工况。`,
      ``,
      `◆ 占空比控制（<50%）：`,
      `  Dmax ≤ 50% ⟺ VOR ≤ Vdc（因为 VOR/(Vdc+VOR) ≤ 0.5）`,
      `  本工具上限设 48%（留裕量），对应 VOR ≤ 0.48·Vdc/(1-0.48) ≈ 0.92·Vdc。`,
      `  若目标 VOR 超过该值，工具自动降到上限，保证 Dmax≤48%。`,
      ``,
      `◆ 为什么压到 <50%：`,
      `  VOR 越高 → Vsw = VdcMax + VOR + 漏感尖峰 越高 → MOSFET 耐压要求越高；`,
      `  且 CCM 下 D>50% 易亚谐波振荡，需加斜坡补偿。`,
    ],
  },
  {
    title: '④ 法拉第定律 → Np 最小值',
    lines: [
      `法拉第电磁感应定律：V = N·Ae·dB/dt，对恒定电压 V 作用时间 t：V·t = N·Ae·ΔB`,
      `在 PWM 中，ON 时间 t_on = D/f：Vdc·(D/fs) = Np·Ae·ΔB`,
      ``,
      `  Np_min = VdcMin · Dmax / (ΔB · Ae · fs)`,
      ``,
      `物理意义：Np 不足时，同样 V·t 下 ΔB 超标 → 磁芯饱和 → μ 骤降 → 电感崩塌 → 电流指数飙升 → 炸机。`,
      `工程中取 Np_real = ceil(Km × Np_min)，Km ≈ 1.5~1.8 留裕量。`,
    ],
  },
  {
    title: '⑤ 次级匝数 Ns 与取整效应',
    lines: [
      `理想匝比 n = Np/Ns，取整后实际匝比为有理数：Ns = round(Np/n)，n_actual = Np_real/Ns`,
      `取整会引入误差——VOR 和 D 都要重新计算（回代校验）：VOR' = (Vo+Vf)·n_actual，Dmax' = VOR'/(Vdc+VOR')。`,
    ],
  },
  {
    title: '⑥ 临界电感 Lcrit —— CCM/DCM 的分界线（精确式）',
    lines: [
      `临界状态：开关管再次导通瞬间，次级电流恰好降到零。`,
      `次级电流下降斜率（OFF 期间）：di/dt = n²(Vo+Vf)/Lp，下降时间 (1-D)/fs，`,
      `下降量 ΔI_sec = n²(Vo+Vf)(1-D)/(Lp·fs)，平均次级电流 Isec_avg = Io/(1-D)。`,
      ``,
      `临界条件（边界三角波峰值=2×平均）：ΔI_sec/2 = Io/(1-D)`,
      `整理得临界电感（精确，含 Vf）：`,
      `  Lcrit = n²·Vo·(Vo+Vf)·(1-D)² / (2·Pout·fs)`,
      `（不再用 Vo² 近似；近似式会偏小约 Vf/(Vo+Vf) ~4% @12V）`,
      ``,
      `Lp > Lcrit → CCM（连续）；Lp < Lcrit → DCM（断续）；Lp = Lcrit → 临界。`,
    ],
  },
  {
    title: '⑦ CCM 模式：峰值/有效值/次级 RMS',
    lines: [
      `平均原边电流 Ilp_avg = Ppri/(Vdc·D)；纹波比 r = ΔIpp/Ilp_avg（取 0.35）。`,
      `峰值 Ipk = Ilp_avg·(1+r/2)；谷值 Ival = Ilp_avg·(1-r/2)。`,
      `原边有效值 Irms = Ipk·√(D·(1+r²/3))。`,
      ``,
      `◆ 次级电流（安匝连续，CCM 为梯形波）：`,
      `  次级峰值 Ispk = n·Ipk_pri；次级谷值 = n·Ival_pri。`,
      `  次级 RMS = √(D'·(Ispk² + Ispk·Ival + Ival²)/3)，其中 D' = (1-D)。`,
      `  （线径选型用次级 RMS，而非 Ispk×0.5 这类粗估。）`,
    ],
  },
  {
    title: '⑧ DCM 模式：峰值电流与次级 RMS',
    lines: [
      `DCM 能量批量传输：E = ½Lp·Ipk²，Ppri = E·fs = ½Lp·Ipk²·fs`,
      `  Ipk = √(2·Ppri/(Lp·fs))`,
      ``,
      `◆ 次级电流（三角波 Ispk→0，放电占空 D'=1-D）：`,
      `  次级峰值 Ispk = n·Ipk_pri；次级 RMS = Ispk·√(D'/3)。`,
      ``,
      `DCM 特性：峰值高、EMI 大，但控制简单、无右半平面零点、轻载效率高。`,
      `所以小功率 (<15W) 常见 DCM，大功率倾向 CCM。`,
    ],
  },
  {
    title: '⑨ 气隙长度 lg —— 为什么必须加气隙？',
    lines: [
      `无气隙铁氧体 μr ~ 2000，L 极大但极易饱和。气隙 μr≈1，磁阻主导：ℜtotal ≈ lg/(μ₀·Ae)。`,
      `电感 Lp = Np²/ℜtotal ≈ Np²·μ₀·Ae/lg  →  反解 lg = Np²·μ₀·Ae/Lp。`,
      `气隙增大磁阻 → 降有效电感 → 增大储能 ½LI²；防饱和；但增大漏感和边缘磁通（proximity effect）。`,
      `因此靠近气隙一侧用 P-S-P 三明治绕法抵消漏磁场。`,
      `⚠ 实际 lg 受骨架/中柱磨隙上限约束（本工具给出参考上限，超限会提示）。`,
    ],
  },
  {
    title: '⑩ 导线截面积选择——电流密度经验法则',
    lines: [
      `电流密度 J 控制在合理范围：自然对流 3~4 A/mm²，强制风冷 5~6，PCB 走线 10~20。`,
      `所需截面积 S = I_rms / J（用真实 RMS，次级也用它）。`,
      `查 AWG 表选 S ≤ 可用规格的最小 AWG；线下搓用多股并绕 N_strand = ceil(S/S_single)。`,
      `本工具 J=4.5A/mm²（自然对流保守值）。`,
    ],
  },
  {
    title: '⑪ 绕组窗口填充校验（能否造）',
    lines: [
      `绕组总截面积：Np·Apri + Ns·Asec（Apri/Asec 为实际用线截面积）。`,
      `真实可绕面积需除以窗口利用率 K_util（含骨架、绝缘、漆包、层间间隙），单端 E 型典型 K≈0.35。`,
      ``,
      `  需要面积 = (Np·Apri + Ns·Asec) / K_util`,
      `  窗口填充率 fill = 需要面积 / Aw   （Aw 为配套骨架绕组窗口面积）`,
      ``,
      `fill > 1 → 放不下 → 换大磁芯或减线径/多股；fill 在 0.3~0.7 较合理。`,
      `工具按"最小能放下的磁芯"自动迭代选择（不再只看功率档）。`,
    ],
  },
  {
    title: '⑫ ΔB 饱和降额（含工作温度）',
    lines: [
      `材料饱和磁密 Bs 是 25℃ 下数值；实际工作温度（铁氧体常 100℃）下 Bs 显著下降。`,
      ``,
      `  Bs@100℃ ≈ Bs(25℃) × 0.75（典型降额）`,
      `  安全判据：工作 ΔB ≤ Bs@100℃ × 0.9（再留裕量）`,
      ``,
      `工作 ΔB = VdcMin·Dmax/(Np·Ae·fs)（法拉第反推，与 Np 实际值一致）。`,
      `若 ΔB 超标 → 磁芯过热/进入饱和区 → 建议降 ΔB、加大 Np 或换大磁芯。`,
      `本工具把 ΔB 与 Bs 安全上限对比并提示。`,
    ],
  },
  {
    title: '⑬ 铜损 / 铁损 / 温升（估算）',
    lines: [
      `◆ 铜损：Pcu = Ipri_rms²·Rpri + Isec_rms²·Rsec`,
      `  绕组电阻 R = ρ_cu · MLT · N / A_wire（ρ_cu=1.72e-8 Ω·m；MLT 为平均匝长；A_wire 为实际线截面积）。`,
      ``,
      `◆ 铁损：Steinmetz 经验式（归一化到 100kHz/ΔB=0.2T → 300mW/cm³）：`,
      `  Pv(mW/cm³) = 300 × (f/100kHz)^1.6 × (ΔB/2/0.1)^2.1`,
      `  Pcore(W) = Pv/1000 × Ve(cm³)`,
      ``,
      `◆ 温升：ΔT ≈ P_total / R_th，R_th 按磁芯体积粗估：R_th ≈ 40/√Ve(cm³) ℃/W。`,
      `  均属估算，实际需实测（绕线/风道/绝缘都会影响）。`,
    ],
  },
  {
    title: '⑭ 漏感与器件应力（选型）',
    lines: [
      `◆ 漏感：Lleak ≈ K_leak·Lp（P-S-P 三明治 K≈1.5~3%，取 2%）。`,
      `  关断时漏感储能释放产生尖峰：Vspike ≈ K_spike·VOR（良好 RCD 钳位 K≈0.25）。`,
      ``,
      `◆ MOSFET 关断压：Vsw = VdcMax + VOR + Vspike`,
      `  需 Vds_rated ≥ Vsw/0.8（留 20% 降额）→ 据此推荐 500V/650V 档。`,
      ``,
      `◆ 次级二极管反压：Vr = VdcMax/n + (Vo+Vf)`,
      `  需 Vr_rated ≥ Vr × 1.3 → 据此推荐肖特基(≤100V)/快恢复(≤400V)/高压整流。`,
    ],
  },
  {
    title: '⑮ 商用流程：为何自动换磁芯',
    lines: [
      `单纯按"功率档"选磁芯不够——同样的 24W 用 EE25/13/7 可能窗口放不下。`,
      `商用把三件事一起校验：窗口填充(fill≤1) + 气隙 ≤ 骨架上限 + ΔB ≤ 材料 100℃ 安全上限。`,
      ``,
      `工具从满足功率的最小磁芯开始，逐个试算，返回第一个三者都通过的；全不过则取最大可用并报"超出"。`,
      `所以输入改变/换磁芯时，结果会自动跳到能落地的方案，而不是给一个"理论可行但造不出来"的数。`,
    ],
  },
]
